# Generated by Django 6.0.2 on 2026-02-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('neuro', 'Нейросети для начинающих'), ('ethernet', 'Ethernet'), ('prompt', 'Prompt Engineering')], default='neuro', max_length=20, verbose_name='Курс')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('lesson_type', models.CharField(choices=[('article', 'Статья'), ('test', 'Тест')], default='article', max_length=10, verbose_name='Тип урока')),
                ('content', models.TextField(blank=True, verbose_name='Содержание статьи')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learningbase.lesson', verbose_name='Урок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=300, verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learningbase.testquestion', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, verbose_name='Сессия пользователя')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='Дата завершения')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningbase.lesson', verbose_name='Урок')),
            ],
            options={
                'unique_together': {('session_key', 'lesson')},
            },
        ),
    ]
