# Generated by Django 6.0.2 on 2026-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningbase', '0002_lesson_testquestion_testanswer_userprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name': 'Ответ теста', 'verbose_name_plural': 'Ответы теста'},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы теста'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Прогресс', 'verbose_name_plural': 'Прогресс'},
        ),
        migrations.AddField(
            model_name='post',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(choices=[('neuro', 'Нейросети для начинающих'), ('ethernet', 'Пользование интернетом'), ('prompt', 'Инженер промтов')], default='neuro', max_length=20, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата-создания'),
        ),
    ]
